setwd("r_programming_sc2/")
hs <- read.csv("hs0.csv")
hs
summary(hs)
attach(hs)
mean(read)
mean(write)
mean(math)
mean(hs)
sd(read)
sd(math)
min(write)
max(write)
range(write)
range(read)
range(math)
quantile(math,.25)
quantile(math,c(.1,.12))
quantile(math,.1,.2)
quantile(math,c(.25,.5,.75))
quantile(math)
quantile(write)
length(write[write<=45])/length(write)*100
summary(write)
sum(write)
summary(read)
summary(math)
summary(science)
summary(hs)
mean(hs)
fivenum(write)
fivenum(math)
x <- rnorm(1000)
y <- rnorm(1000,2,.1)
x
y
cor(x,y)
cor(mtcars,use = "complete.obs",method = "kendall")
cov(mtcars,use = "complete.obs")
cov(mtcars)
